version: "3.8"
services:
  postgres:
    image: postgis/postgis:13-3.1-alpine
    container_name: postgres-example
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
